### ISSUE TITLE
abeebus.py:31: DeprecationWarning: 'U' mode is deprecated

### ISSUE THREAD

**Issue by KDPryor** [13Cubed/Abeebus#2]
Hello,

Using Abeebus with Python 3.7.0 causes this error output.
`abeebus.py:31: DeprecationWarning: 'U' mode is deprecated
  f = open(filename, 'rU')
Traceback (most recent call last):
  File "abeebus.py", line 161, in <module>
    main()
  File "abeebus.py", line 156, in main
    printData(output)
  File "abeebus.py", line 107, in printData
    rows = list(csv.reader(resultsNoUnicode))
_csv.Error: iterator should return strings, not bytes (did you open the file in text mode?)`

The error does not occur in Python 2.7. My Python ability is poor, so I don't know how to fix it. The tool works very well in Python 2.7 and I appreciate you making it available.

**Comment by 13Cubed** [comment]
Try the newest version, 2.0, which has just been released. It's re-written in Python 3, and much more efficient.
